; Установщик Livecraft (CLAUDE.md §13 этап 8, §14 решения 16, 24, 37). Собирается build_release.bat:
; ISCC /DAppVersion=<версия> livecraft.iss — номер версии берётся только из app\version.py.
;
; Ставит без прав администратора в {localappdata}\Programs\Livecraft (папка программы должна быть с правом записи —
; рядом с exe программа держит свои данные, §5); папку можно выбрать при первой установке. Язык мастера и названия ярлыков — по языку
; Windows (ru, uk, иначе en), окна выбора языка нет. Ярлыки (§14 решение 53): в меню «Пуск», в группе Livecraft, —
; «Livecraft», «пробный запуск» и «настройка»; на рабочем столе — только «Livecraft» и «Livecraft — настройка», прежний
; ярлык пробного запуска со стола установка поверх удаляет. «Livecraft» и «пробный запуск» — через livecraft.bat (без
; паузы окно консоли закрылось бы вместе с программой), «настройка» — оконный livecraftw.exe. Двойной щелчок по .bcast —
; livecraft.bat "<файл>". Иконка Livecraft (app\resources\icon\livecraft.ico) — у установщика, у обоих exe (livecraft.spec),
; от них — у ярлыков и у файлов .bcast. У каждого ярлыка — свой AppUserModelID «Livecraft.<ярлык>»: без него Windows
; называет записи ярлыка с аргументами (плитка «Пуска», список переходов, счёт переключений) id
; Microsoft.AutoGenerated.{…}, по которому удаление их не узнает.
;
; Кладёт только файлы программы: livecraft.exe, livecraftw.exe, _internal\, livecraft.bat, tools\ и
; secrets\client_secret.json («паспорт программы», один на всех, §9 — заменяется при каждой установке). Описания
; программы в установке нет (§14 решение 55): мастер его не показывает и в папку программы не кладёт, прежнее
; установка поверх удаляет.
;
; Обновление (§14 решение 56) — новая версия ставится поверх: мастер папку не спрашивает и ставит в ту же
; (DisableDirPage=auto), программная часть меняется — exe и livecraft.bat заменяются, _internal\ стирается и кладётся
; заново целиком (файлов прежней версии в нём не остаётся); данные человека (secrets\, logs\, bcast\, image\, docs\,
; tokens\, keystreams\, state\) и tools\ (yt-dlp и deno программа обновляет сама) остаются.
;
; Удаление (§14 решение 56) не оставляет ничего: стирает в папке программы папки ролей (app\paths.py::DataDir) и
; _internal\, затем саму папку, если в ней ничего не осталось; в реестре — ключи .bcast и Livecraft.Package, всё, что
; Windows привязала к типам .bcast и .lctoken, свойства плиток «Пуска» и значения истории Windows в HKCU, названные
; путём в папке программы, ярлыком Livecraft, его AppUserModelID или установщиком livecraft-setup-* ([Code]). Не трогает: чужие файлы в папке программы (установка
; в общую папку иначе стёрла бы чужое), папки, выбранные в настройке вне папки программы (§14 решение 37), и HKLM
; (BAM): без прав администратора его не изменить.

#ifndef AppVersion
  #error AppVersion не передан: номер версии берётся только из app\version.py через build_release.bat
#endif

#define RepoRoot RemoveBackslash(SourcePath)
#define SourceDir RepoRoot + "\dist\livecraft"

[Setup]
AppId={{772A767C-95AD-46C5-95CD-C9E1B6F21507}
AppName=Livecraft
AppVersion={#AppVersion}
AppVerName=Livecraft {#AppVersion}
DefaultDirName={localappdata}\Programs\Livecraft
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog commandline
DisableDirPage=auto
UsePreviousAppDir=yes
DisableProgramGroupPage=yes
OutputDir=dist\installer
OutputBaseFilename=livecraft-setup-{#AppVersion}
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayName=Livecraft {#AppVersion}
UninstallDisplayIcon={app}\livecraft.exe
SetupIconFile={#RepoRoot}\app\resources\icon\livecraft.ico
CloseApplications=yes
RestartIfNeededByRun=no
ShowLanguageDialog=no
LanguageDetectionMethod=uilanguage
ChangesAssociations=yes

[Languages]
; Первый язык — и язык Windows, которого нет в списке.
Name: "en"; MessagesFile: "compiler:Default.isl"
Name: "ru"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "uk"; MessagesFile: "compiler:Languages\Ukrainian.isl"

[CustomMessages]
en.ShortcutRun=Livecraft
en.ShortcutDryRun=Livecraft — dry run
en.ShortcutSetup=Livecraft — setup
en.PackageFileType=Livecraft package
ru.ShortcutRun=Livecraft
ru.ShortcutDryRun=Livecraft — пробный запуск
ru.ShortcutSetup=Livecraft — настройка
ru.PackageFileType=Пакет Livecraft
uk.ShortcutRun=Livecraft
uk.ShortcutDryRun=Livecraft — пробний запуск
uk.ShortcutSetup=Livecraft — налаштування
uk.PackageFileType=Пакет Livecraft

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Dirs]
; Папка пакетов: владелец канала кладёт туда пакет ещё до первого запуска.
Name: "{app}\bcast"

[Files]
Source: "{#SourceDir}\livecraft.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\livecraftw.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourceDir}\livecraft.bat"; DestDir: "{app}"; Flags: ignoreversion
; yt-dlp и deno программа обновляет сама: установка поверх не возвращает старые, а только кладёт недостающие.
Source: "{#SourceDir}\tools\yt-dlp.exe"; DestDir: "{app}\tools"; Flags: onlyifdoesntexist
Source: "{#SourceDir}\tools\deno.exe"; DestDir: "{app}\tools"; Flags: onlyifdoesntexist
Source: "{#SourceDir}\secrets\client_secret.json"; DestDir: "{app}\secrets"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\Livecraft\{cm:ShortcutRun}"; Filename: "{app}\livecraft.bat"; WorkingDir: "{app}"; IconFilename: "{app}\livecraft.exe"; AppUserModelID: "Livecraft.Run"
Name: "{autoprograms}\Livecraft\{cm:ShortcutDryRun}"; Filename: "{app}\livecraft.bat"; Parameters: "--dry-run"; WorkingDir: "{app}"; IconFilename: "{app}\livecraft.exe"; AppUserModelID: "Livecraft.DryRun"
Name: "{autoprograms}\Livecraft\{cm:ShortcutSetup}"; Filename: "{app}\livecraftw.exe"; Parameters: "--setup"; WorkingDir: "{app}"; AppUserModelID: "Livecraft.Setup"
Name: "{autodesktop}\{cm:ShortcutRun}"; Filename: "{app}\livecraft.bat"; WorkingDir: "{app}"; IconFilename: "{app}\livecraft.exe"; AppUserModelID: "Livecraft.Run"; Tasks: desktopicon
Name: "{autodesktop}\{cm:ShortcutSetup}"; Filename: "{app}\livecraftw.exe"; Parameters: "--setup"; WorkingDir: "{app}"; AppUserModelID: "Livecraft.Setup"; Tasks: desktopicon

[InstallDelete]
; Ярлык пробного запуска на рабочем столе ставила версия 0.1.1; Inno Setup сам ярлыков прежней версии не удаляет.
Type: files; Name: "{autodesktop}\{cm:ShortcutDryRun}.lnk"
; Описание программы версии 0.1.x клали в папку программы; с 0.1.3 его нет (§14 решение 55).
Type: files; Name: "{app}\README.md"
; Программная часть заменяется целиком: файлы прежней версии, которых нет в новой, не остаются. Папок данных и tools\
; здесь нет — обновление стёрло бы данные.
Type: filesandordirs; Name: "{app}\_internal"

[UninstallDelete]
; Папки ролей (app\paths.py::DataDir) и программная часть; затем папка программы, если в ней ничего не осталось —
; файлы удаления Inno Setup убирает после этого шага и повторяет удаление папки. Записи на {app} целиком нет: в общей
; папке она стёрла бы чужие файлы.
Type: filesandordirs; Name: "{app}\secrets"
Type: filesandordirs; Name: "{app}\tools"
Type: filesandordirs; Name: "{app}\image"
Type: filesandordirs; Name: "{app}\bcast"
Type: filesandordirs; Name: "{app}\docs"
Type: filesandordirs; Name: "{app}\tokens"
Type: filesandordirs; Name: "{app}\keystreams"
Type: filesandordirs; Name: "{app}\state"
Type: filesandordirs; Name: "{app}\logs"
Type: filesandordirs; Name: "{app}\_internal"
Type: dirifempty; Name: "{app}"

[Registry]
; Ассоциация .bcast — у того, кто ставит (без прав администратора — HKCU\Software\Classes).
Root: HKA; Subkey: "Software\Classes\.bcast"; ValueType: string; ValueName: ""; ValueData: "Livecraft.Package"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\Livecraft.Package"; ValueType: string; ValueName: ""; ValueData: "{cm:PackageFileType}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\Livecraft.Package\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: """{app}\livecraft.exe"",0"
Root: HKA; Subkey: "Software\Classes\Livecraft.Package\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\livecraft.bat"" ""%1"""

[Messages]
; Окно подтверждения удаления называет данные, которые уйдут, и что для обновления удалять не нужно (§14 решение 56).
en.ConfirmUninstall=Remove %1 together with all data in the program folder: settings, vault, channel sign-ins, tokens, packages, previews, document copies, keys and logs?%n%nNo need to remove it for an update: a new version installs over this one and keeps the data.
ru.ConfirmUninstall=Удалить %1 вместе со всеми данными в папке программы: настройками, сейфом, входами каналов, токенами, пакетами, превью, копиями документов, ключами и логами?%n%nДля обновления удалять не нужно: новая версия ставится поверх и данные сохраняет.
uk.ConfirmUninstall=Видалити %1 разом з усіма даними в папці програми: налаштуваннями, сейфом, входами каналів, токенами, пакетами, превʼю, копіями документів, ключами та логами?%n%nДля оновлення видаляти не потрібно: нова версія ставиться поверх і зберігає дані.

[Code]
// Следы Livecraft, которые Windows записала в реестр пользователя (§14 решение 56), — после удаления файлов.
// Ключи под типы .bcast и .lctoken и под exe программы удаляются целиком; в ключах истории Windows удаляется только
// значение, которое указывает на Livecraft (PointsToLivecraft), — чужие остаются; свойства плиток «Пуска» — ключи
// плиток Livecraft. HKLM (BAM) без прав администратора не меняется.

const
  // Ключи HKCU, которые Windows завела под типы файлов Livecraft и под её exe.
  OwnKeys =
    'Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.bcast|' +
    'Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.lctoken|' +
    'Software\Microsoft\Windows\CurrentVersion\Explorer\RecentDocs\.bcast|' +
    'Software\Microsoft\Windows\CurrentVersion\Explorer\RecentDocs\.lctoken|' +
    'Software\Microsoft\Windows\CurrentVersion\Explorer\ComDlg32\OpenSavePidlMRU\bcast|' +
    'Software\Microsoft\Windows\CurrentVersion\Explorer\ComDlg32\OpenSavePidlMRU\lctoken|' +
    'Software\Classes\Applications\livecraft.exe|' +
    'Software\Classes\Applications\livecraftw.exe|' +
    'Software\Classes\bcast_auto_file|' +
    'Software\Classes\lctoken_auto_file';
  // Ключи истории Windows, где имя значения — путь к запущенному файлу или AppUserModelID ярлыка (в UFH\SHC путь лежит
  // в данных значения).
  HistoryKeys =
    'Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\MuiCache|' +
    'Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store|' +
    'Software\Microsoft\Windows\CurrentVersion\UFH\SHC|' +
    'Software\Microsoft\Windows\CurrentVersion\Search\JumplistData';
  UserAssistKey = 'Software\Microsoft\Windows\CurrentVersion\Explorer\UserAssist';
  FeatureUsageKey = 'Software\Microsoft\Windows\CurrentVersion\Explorer\FeatureUsage';
  ToastsKey = 'Software\Microsoft\Windows\CurrentVersion\ApplicationAssociationToasts';
  // Свойства плиток «Пуска»: ключ — TilePrefix + AppUserModelID или путь цели ярлыка (путь — цепочкой ключей по папкам).
  TilesKey = 'Software\Microsoft\Windows\CurrentVersion\Start\TileProperties';
  TilePrefix = 'W~';
  // Начало AppUserModelID ярлыков Livecraft ([Icons]).
  AppIdPrefix = 'Livecraft.';
  // Известные папки, GUID которых Windows ставит в начало пути в UserAssist и FeatureUsage: GUID=папка.
  KnownFolders =
    'A77F5D77-2E2B-44C3-A6A2-ABA601054A51={userprograms}|' +
    'B4BFCC3A-DB2C-424C-B029-7FE99A87C641={userdesktop}|' +
    '5CD7AEE2-2219-4A67-B85D-6C9CE15660CB={localappdata}\Programs|' +
    '0139D44E-6AFE-49F2-8690-3DAFCAE6FFB8={commonprograms}|' +
    'C4AA340D-F20F-4863-AFEF-F87EF2E6BA25={commondesktop}';
  ListSeparator = '|';
  PairSeparator = '=';

// Первый элемент списка `List` (разделитель ListSeparator); сам элемент из `List` убирается.
function TakeItem(var List: String): String;
var
  P: Integer;
begin
  P := Pos(ListSeparator, List);
  if P = 0 then
  begin
    Result := List;
    List := '';
  end
  else
  begin
    Result := Copy(List, 1, P - 1);
    Delete(List, 1, P);
  end;
end;

function StartsText(const Prefix, S: String): Boolean;
begin
  Result := AnsiLowercase(Copy(S, 1, Length(Prefix))) = AnsiLowercase(Prefix);
end;

// Имена значений UserAssist записаны ROT13.
function Rot13(const S: String): String;
var
  I: Integer;
  C: Char;
begin
  Result := S;
  for I := 1 to Length(Result) do
  begin
    C := Result[I];
    if ((C >= 'A') and (C <= 'M')) or ((C >= 'a') and (C <= 'm')) then
      Result[I] := Chr(Ord(C) + 13)
    else if ((C >= 'N') and (C <= 'Z')) or ((C >= 'n') and (C <= 'z')) then
      Result[I] := Chr(Ord(C) - 13);
  end;
end;

// '{GUID}\остаток' известной папки — путь этой папки и остаток; прочее — как есть.
function KnownFolderPath(const Name: String): String;
var
  Folders, Pair, Guid: String;
  P: Integer;
begin
  Result := Name;
  P := Pos('}', Name);
  if (Copy(Name, 1, 1) <> '{') or (P = 0) then
    Exit;
  Guid := Copy(Name, 2, P - 2);
  Folders := KnownFolders;
  while Folders <> '' do
  begin
    Pair := TakeItem(Folders);
    if CompareText(Copy(Pair, 1, Pos(PairSeparator, Pair) - 1), Guid) = 0 then
    begin
      Result := ExpandConstant(Copy(Pair, Pos(PairSeparator, Pair) + 1, MaxInt)) + Copy(Name, P + 1, MaxInt);
      Exit;
    end;
  end;
end;

// Ярлык Livecraft прямо на рабочем столе: Livecraft*.lnk.
function IsDesktopShortcut(const Path: String): Boolean;
var
  Desktop, Rest: String;
begin
  Desktop := AddBackslash(ExpandConstant('{autodesktop}'));
  Rest := AnsiLowercase(Copy(Path, Length(Desktop) + 1, MaxInt));
  Result := StartsText(Desktop, Path) and (Pos('\', Rest) = 0) and StartsText('livecraft', Rest)
    and (Copy(Rest, Length(Rest) - 3, 4) = '.lnk');
end;

// Имя указывает на Livecraft: путь в папке программы, в группе Livecraft меню «Пуск», ярлык Livecraft на рабочем
// столе, файл установщика livecraft-setup-* (и его временная копия) или AppUserModelID ярлыка Livecraft. Без учёта
// регистра.
function PointsToLivecraft(const Name: String): Boolean;
var
  Path: String;
begin
  Path := KnownFolderPath(Name);
  Result := StartsText(AddBackslash(ExpandConstant('{app}')), Path)
    or StartsText(ExpandConstant('{autoprograms}\Livecraft\'), Path)
    or IsDesktopShortcut(Path)
    or StartsText('livecraft-setup-', ExtractFileName(Path))
    or StartsText(AppIdPrefix, Name);
end;

// Данные значения — список строк, и одна из них указывает на Livecraft (UFH\SHC: ярлык и его цель).
function DataPointsToLivecraft(const SubKey, Name: String): Boolean;
var
  Data, Item: String;
  P: Integer;
begin
  Result := False;
  if not RegQueryMultiStringValue(HKCU, SubKey, Name, Data) then
    Exit;
  Data := Data + #0;
  P := Pos(#0, Data);
  while (P > 0) and not Result do
  begin
    Item := Copy(Data, 1, P - 1);
    Result := (Item <> '') and PointsToLivecraft(Item);
    Delete(Data, 1, P);
    P := Pos(#0, Data);
  end;
end;

// Значения ключа, которые указывают на Livecraft; `IsRot13` — имена записаны ROT13 (UserAssist).
procedure DeleteLivecraftValues(const SubKey: String; IsRot13: Boolean);
var
  Names: TArrayOfString;
  Name: String;
  I: Integer;
begin
  if not RegGetValueNames(HKCU, SubKey, Names) then
    Exit;
  for I := 0 to GetArrayLength(Names) - 1 do
  begin
    Name := Names[I];
    if IsRot13 then
      Name := Rot13(Name);
    if PointsToLivecraft(Name) or DataPointsToLivecraft(SubKey, Names[I]) then
      RegDeleteValue(HKCU, SubKey, Names[I]);
  end;
end;

// Подключи ключа: в каждом (с хвостом `Tail`) — значения, которые указывают на Livecraft.
procedure DeleteLivecraftValuesUnder(const SubKey, Tail: String; IsRot13: Boolean);
var
  Names: TArrayOfString;
  I: Integer;
begin
  if not RegGetSubkeyNames(HKCU, SubKey, Names) then
    Exit;
  for I := 0 to GetArrayLength(Names) - 1 do
    DeleteLivecraftValues(SubKey + '\' + Names[I] + Tail, IsRot13);
end;

// Отметки уведомлений «новое приложение для типа»: имя — <программа>_.bcast или <программа>_.lctoken.
procedure DeleteTypeToasts;
var
  Names: TArrayOfString;
  Name: String;
  I: Integer;
begin
  if not RegGetValueNames(HKCU, ToastsKey, Names) then
    Exit;
  for I := 0 to GetArrayLength(Names) - 1 do
  begin
    Name := AnsiLowercase(Names[I]);
    if (Copy(Name, Length(Name) - 6, 7) = '_.bcast') or (Copy(Name, Length(Name) - 8, 9) = '_.lctoken') then
      RegDeleteValue(HKCU, ToastsKey, Names[I]);
  end;
end;

// Ключ на уровень выше: `Key` без последнего '\имя'.
function ParentKey(const Key: String): String;
var
  I: Integer;
begin
  I := Length(Key);
  while (I > 0) and (Key[I] <> '\') do
    I := I - 1;
  Result := Copy(Key, 1, I - 1);
end;

// Плитки «Пуска» Livecraft: по пути в папке программы (и ставшие пустыми ключи папок над ним) и по AppUserModelID.
procedure DeleteStartTiles;
var
  Names: TArrayOfString;
  Key: String;
  I: Integer;
begin
  Key := TilesKey + '\' + TilePrefix + RemoveBackslash(ExpandConstant('{app}'));
  RegDeleteKeyIncludingSubkeys(HKCU, Key);
  Key := ParentKey(Key);
  while (Length(Key) > Length(TilesKey)) and RegDeleteKeyIfEmpty(HKCU, Key) do
    Key := ParentKey(Key);
  if not RegGetSubkeyNames(HKCU, TilesKey, Names) then
    Exit;
  for I := 0 to GetArrayLength(Names) - 1 do
    if StartsText(TilePrefix + AppIdPrefix, Names[I]) then
      RegDeleteKeyIncludingSubkeys(HKCU, TilesKey + '\' + Names[I]);
end;

procedure DeleteRegistryTraces;
var
  Keys: String;
begin
  Keys := OwnKeys;
  while Keys <> '' do
    RegDeleteKeyIncludingSubkeys(HKCU, TakeItem(Keys));
  Keys := HistoryKeys;
  while Keys <> '' do
    DeleteLivecraftValues(TakeItem(Keys), False);
  DeleteLivecraftValuesUnder(UserAssistKey, '\Count', True);
  DeleteLivecraftValuesUnder(FeatureUsageKey, '', False);
  DeleteTypeToasts;
  DeleteStartTiles;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
    DeleteRegistryTraces;
end;
