"""Скрипт установщика livecraft.iss держит удаление без следов и обновление без потери данных (§14 решение 56)."""
from __future__ import annotations

import re
from pathlib import Path

from app.paths import DataDir
from app.version import APP_NAME

ISS_FILE: Path = Path(__file__).resolve().parents[2] / f"{APP_NAME}.iss"      # скрипт назван по программе
PROGRAM_PART: str = "_internal"
APP_ID_PREFIX: re.Pattern[str] = re.compile(r"^\s*AppIdPrefix = '([^']+)';", re.MULTILINE)   # начало AppUserModelID в [Code]


def section(name: str) -> list[dict[str, str]]:
    """Записи секции `[name]`: каждая строка — словарь «параметр → значение» без кавычек; комментарии пропущены."""
    entries: list[dict[str, str]] = []
    inside: bool = False
    for raw in ISS_FILE.read_text(encoding="utf-8-sig").splitlines():
        line: str = raw.strip()
        if line.startswith("["):
            inside = line == f"[{name}]"
            continue
        if not inside or not line or line.startswith(";"):
            continue
        pairs: list[list[str]] = [part.split(":", 1) for part in line.split(";") if ":" in part]
        entries.append({key.strip(): value.strip().strip('"') for key, value in pairs})
    return entries


def test_uninstall_deletes_every_data_folder_and_the_program_part() -> None:
    """Новая папка роли без строки удаления осталась бы следом после удаления программы."""
    deleted: set[str] = {entry["Name"] for entry in section("UninstallDelete") if entry["Type"] == "filesandordirs"}
    expected: set[str] = {f"{{app}}\\{folder.value}" for folder in DataDir} | {f"{{app}}\\{PROGRAM_PART}"}
    assert expected <= deleted


def test_uninstall_ends_with_the_program_folder_only_if_it_is_empty() -> None:
    entries: list[dict[str, str]] = section("UninstallDelete")
    assert entries[-1] == {"Type": "dirifempty", "Name": "{app}"}


def test_uninstall_never_wipes_the_program_folder_as_a_whole() -> None:
    """В общей папке удаление {app} целиком или подстановкой стёрло бы чужие файлы."""
    for entry in section("UninstallDelete"):
        name: str = entry["Name"]
        assert "*" not in name and "?" not in name
        assert name != "{app}" or entry["Type"] == "dirifempty"


def test_an_update_keeps_the_data_folders_and_replaces_the_program_part() -> None:
    """Установка поверх стирает только программную часть: папка данных в [InstallDelete] стёрла бы данные."""
    names: set[str] = {entry["Name"] for entry in section("InstallDelete")}
    assert not names & {f"{{app}}\\{folder.value}" for folder in DataDir}
    assert f"{{app}}\\{PROGRAM_PART}" in names
    assert not any(name.startswith(f"{{app}}\\{DataDir.TOOLS.value}") for name in names)


def test_every_shortcut_has_an_app_id_the_uninstall_recognizes() -> None:
    """Без своего AppUserModelID Windows называет записи ярлыка с аргументами (плитка «Пуска», список переходов)
    id Microsoft.AutoGenerated.{…}, и удаление их не узнаёт; один ярлык на столе и в «Пуске» — один id."""
    match: re.Match[str] | None = APP_ID_PREFIX.search(ISS_FILE.read_text(encoding="utf-8-sig"))
    assert match is not None
    ids: dict[tuple[str, str], set[str]] = {}
    for entry in section("Icons"):
        assert entry["AppUserModelID"].startswith(match.group(1))
        ids.setdefault((entry["Filename"], entry.get("Parameters", "")), set()).add(entry["AppUserModelID"])
    assert all(len(found) == 1 for found in ids.values())
    assert len({next(iter(found)) for found in ids.values()}) == len(ids)
